<img src="img/usmlogo.png" style="float:right;height:100px">
<img src="img/dilogo.png" style="float:left;height:100px">
<center>
    <h1> Laboratorio 4 </h1>
    <h2> Profesor: Ricardo Ñanculef </h2>
    <h3> Ayudante: Gabriel Ortega </h3>
    <h4> Alumno ; Rol ; Malla </h4>
    <h4> Alumno2 ; Rol ; Malla </h4>
</center>
<p>
<center><h4>_Fecha_</h4></center>
</p>

## Instrucciones


La modalidad de trabajo será mediante el uso de jupyter notebook. El notebook debe ser desarrollado en parejas o individual pero solamente una de esas modalidades (Pueden cambiar de compañero o modalidad en cada laboratorio). Este laboratorio debe ser entregado a más tardar el día Viernes 21 de Noviembre, no se aceptan entregas enviadas al correo del ayudante.

La **modalidad de entrega será un archivo Apellido1_Apellido2_Lab4.zip/.tar.gz/rar** que contenga un notebook que incluya todas las preguntas con sus respectivas respuestas + un README que indique la forma correcta de ejecutar su notebook. Este notebook presenta ciertas preguntas marcadas con **O:** que indican que para los alumnos de malla nueva es opcional, pero obligatoria para los alumnos de malla vieja. En el caso de haber una pareja con un integrante de malla nueva y uno de malla vieja, se considera malla vieja. El laboratorio puede ser trabajado tanto en lenguaje R como en lenguaje python (para los que usen python 2.X, absténganse a las consecuencias). Lea bien el enunciado y se recuerda que el lenguaje oficial del curso es R, por lo que quejas sobre funcionalidades en python no aplican (en caso de haber).

Su notebook debe incluir un encabezado como el presente en este notebook (Si utilizará las imagenes recuerde adjuntar la carpeta de imagenes o borrarlas del markdown), **para la malla debe colocar INF-280 o ILI-280** según corresponda (no ponga otras cosas o se descontará). 

**Cualquier copia detectada implicará reprobación del laboratorio con nota 0 (lo que implica reprobar el ramo con nota 0) además de la notificación correspondiente al Profesor.** 

## 1. Contraste de Hipótesis (25p)

Sus compañeros se encontraban discutiendo sobre su experiencia en el laboratorio de un ramo de estadística que cursaron en el pasado, estas afirmaciones están basadas en su experiencia, pero ellos hablaban como si estuvieran incluyendo a todas las generaciones.

<br>
<center>
1. Estoy seguro que el laboratorio 4 tiene peores notas que el laboratorio 3
</center>
<br>
<center>
2. La proporción entre los que aprobaron el laboratorio 1 y los que aprobaron el laboratorio 2 es la misma.
</center>
<br>
<center>
3. Recuerdo que el laboratorio 2 fue más disperso que el laboratorio 4.
</center>

Como usted cuenta con las notas que sus compañeros obtuvieron en el laboratorio (laboratorio.csv) ha decidido verificar que tan válidas son estas afirmaciones mediante un test de hipótesis para cada una.

>abc) Realice un contraste de hipótesis para determinar si lo que dicen sus compañeros tiene validez o no. Utilice funciones provistas por los lenguajes explicando brevemente lo que hacen y su interpretación del resultado arrojado.

>**O:** d) Investigue en lo que consiste un permutation test y utilicelo en alguna (solo 1, no las 3) de las 3 afirmaciones de sus compañeros. Puede comparar con el trabajo previo.

## 2. Regresión Lineal Simple y Bootstrap

### 2.1 Regresión Lineal (35p)

Uno de los aspectos más importantes de estadística es el análisis de la relación entre dos variables, uno de los modelos más simples para esto es la *Regresión Lineal Simple*.

La regresión lineal simple de mínimos cuadrados es un modelo para representar una relación lineal entre dos variables mediante la ecuación: $Y = a\cdot X + b + \epsilon$.

En esta sección se trabajará con un dataset (datos.csv) que contiene 3 variables: X, Y, Z. El objeto de estudio es determinar si un modelo de regresión lineal es bueno para explicar las relaciones entre X e Y y entre X y Z. 

$$ Y = F(x) \; \;Z = F(x) $$

>a) Cargue los datos y realice un boxplot por separado para cada variable. ¿Observa algun outlier? ¿Qué efecto tendría un outlier a la hora de realizar el modelo?

In [2]:



datos = read.csv("~/library/datos.csv") 




#boxplot
datos$X <- as.numeric(datos$X)
library(ggplot2)

#boxplot
ggplot(datos, aes(x=" ", y=X)) + ggtitle("Variable X") + 
    geom_boxplot() + 
    xlab("X") + ylab("Valores")
 

ggplot(datos, aes(x=" ", y=Y)) + ggtitle("Variable Y") + 
    geom_boxplot() + 
    xlab("Y") + ylab("Valores")

ggplot(datos, aes(x=" ", y=Z)) + ggtitle("Variable Z") + 
    geom_boxplot() + 
    xlab("Z") + ylab("Valores")
 

No se observan outliers, de haberlos modificarian la curva de nuestra regresión lineal, alejandola de los datos.

>b) Calcule la covarianza entre X e Y y entre X y Z. ¿Qué puede decir respecto a lo obtenido?

In [14]:
cov_x_y = cov(datos$X, datos$Y)
cov_x_Z = cov(datos$X, datos$Z)

cat("Covarianza X,Y : ",cov_x_y, "\n")
cat("Covarianza X,Z : ",cov_x_Z, "\n")

Covarianza X,Y :  167239 
Covarianza X,Z :  83728.99 


Covarianza X,Y :  167239 


Covarianza X,Z :  83728.99 

Tanto X,Y como X,Z estan relacionadas de manera lineal

>c) Calcule la correlación entre X e Y y entre X y Z. En base a lo obtenido ¿Cree que el modelo de regresión lineal debería ser bueno para ambos casos? ¿A qué conclusión hubiera llegado si solamente calculaba la correlación entre X y Z cuando X es positivo? ¿Es el coeficiente de correlación un buen indicador para todos los casos?

In [15]:
X = datos$X
Y = datos$Y
Z = datos$Z

cat("Correlación X,Y : ",cor(X, Y), "\n")
cat("Correlación X,Z : ",cor(X, Z), "\n")


datos_positivos = subset(datos, X>0)


cat("Correlación X Positivos ,Z : ",cor(datos_positivos$X, datos_positivos$Z), "\n")



Correlación X,Y :  0.9999648 
Correlación X,Z :  0.003875823 
Correlación X Positivos ,Z :  0.9684869 


Correlación X,Y :  0.9999648 

Correlación X,Z :  0.003875823 

Correlación X Positivos ,Z :  0.9684869 

El modelo para X,Y si deberia ser bueno ya que la relación es cercana a 1, para X,Z no ya que la correlación tiende a 0. Si solo se calculaba la correlación entre Z,Z con X > 0 la conclusión sería que el modelo si deberia ser bueno par X,Z.

El coeficiende de correlación no es siempre bueno, ya que este solo coincide cuando ambas variables tienen la misma escala.

>d) **O:** ¿Cuál debería ser el comportamiento de un gráfico *"Valor verdadero vs Prediccion"* de un **buen** modelo? 

Deberian ser 2 lineas sobrepuestas.

>e) Haga un scatterplot de (X,Y) y (X,Z). Respecto a lo que observa ¿Mantiene su postura respecto a las preguntas anteriores?

In [16]:
ggplot(datos, aes(x=X, y=Y)) + geom_point(size=0.01) +  ggtitle("Scatterplot X,Y ") 

ggplot(datos, aes(x=X, y=Z)) + geom_point(size=0.01) +  ggtitle("Scatterplot X,Z ") 


Si mantenemos nuestra postura.

>f) Construya ambos modelos de regresión lineal, obteniendo los coeficientes respectivos.

In [17]:
ModeloXY <- lm(Y ~ X, data=datos) 
ModeloXY

ModeloXZ <- lm(Z ~ X, data=datos) 
ModeloXZ



Call:
lm(formula = Y ~ X, data = datos)

Coefficients:
(Intercept)            X  
      3.038        2.001  



Call:
lm(formula = Z ~ X, data = datos)

Coefficients:
(Intercept)            X  
  83499.745        1.002  


Para el Modelo X,Y el valor de la pendiente es 2.001 y el intercepto 3.038

Para el Modelo X,Z el valor de la pendiente es 1.002 y el intercepto 83499

>g) Grafique las predicciones y valores verdaderos de los datos para ambas variables (un gráfico para cada variable) y comente lo que observa. Respecto a la variable Z, ¿La certeza de las predicciones es homogénea o existen zonas de mayor error y de menor error?

In [18]:
ggplot(datos, aes(x=X, y=Y)) + geom_point(size=0.01) +  ggtitle("Valor Verdadero VS Modelo (X,Y) ") +  geom_smooth(method='lm')


ggplot(datos, aes(x=X, y=Z)) + geom_point(size=0.01) +  ggtitle("Valor Verdadero VS Modelo (X,Z) ") +  geom_smooth(method='lm')


Cercano a los puntos 300, -300 la certeza es mucho mayor que en el resto de los puntos.

>h) Se tienen 4 grupos de inputs (x): 

$$ G_{1} \in [-500,-251] \; G_{2} \in [-250,0] \; G_{3} \in [1,250]\; y \; G_{4} \in [251,500] $$

Calcule el MSE (*Mean Standard Error*) para cada grupo en ambos modelos, comente y concluya respecto al comportamiendo de un modelo de regresión lineal en ambos casos. Además grafique los errores punto a punto.

*Hint: Tiene relación con lo preguntado en g)*

$$ MSE = \frac{\sum \left(\hat{Y_{i}}- Y_{i}\right)^{2}}{n} $$

$$\hat{Y}: \; prediccion$$

$$Y: \; valor\, verdadero$$

In [19]:

MSE_X_Y_G1 = 0
MSE_X_Y_G2 = 0
MSE_X_Y_G3 = 0
MSE_X_Y_G4 = 0
MSE_X_Z_G1 = 0
MSE_X_Z_G2 = 0
MSE_X_Z_G3 = 0
MSE_X_Z_G4 = 0

n = 250

funcionXY = function(x) { 2.001*x + 3.038 }
funcionXZ = function(x) { 1.002*x + 83499.745 }



for(i in 1:n){ 
  
    
    MSE_X_Y_G1 =   MSE_X_Y_G1  + (datos[i+0,]$Y - funcionXY(-501+i))**2
    MSE_X_Y_G2 =   MSE_X_Y_G2  + (datos[i+250,]$Y - funcionXY(-251+i))**2
    MSE_X_Y_G3 =   MSE_X_Y_G3  + (datos[i+500,]$Y - funcionXY(0+i))**2
    MSE_X_Y_G4 =   MSE_X_Y_G4  + (datos[i+750,]$Y - funcionXY(250+i))**2
    
    
    MSE_X_Z_G1 =   MSE_X_Z_G1  + (datos[i+0,]$Z - funcionXZ(-501+i))**2
    MSE_X_Z_G2 =   MSE_X_Z_G2  + (datos[i+250,]$Z - funcionXZ(-251+i))**2
    MSE_X_Z_G3 =   MSE_X_Z_G3  + (datos[i+500,]$Z - funcionXZ(0+i))**2
    MSE_X_Z_G4 =   MSE_X_Z_G4  + (datos[i+750,]$Z - funcionXZ(250+i))**2
    
}


MSE_X_Y_G1 = MSE_X_Y_G1/n
MSE_X_Y_G2 = MSE_X_Y_G2/n
MSE_X_Y_G3 = MSE_X_Y_G3/n
MSE_X_Y_G4 = MSE_X_Y_G4/n
MSE_X_Z_G1 = MSE_X_Z_G1/n
MSE_X_Z_G2 = MSE_X_Z_G2/n
MSE_X_Z_G3 = MSE_X_Z_G3/n
MSE_X_Z_G4 = MSE_X_Z_G4/n

cat("MSE X,Y G1: ", MSE_X_Y_G1 ,"\n")
cat("MSE X,Y G2: ", MSE_X_Y_G2 ,"\n")
cat("MSE X,Y G3: ", MSE_X_Y_G3 ,"\n")
cat("MSE X,Y G4: ", MSE_X_Y_G4 ,"\n")
cat("MSE X,Z G1: ", MSE_X_Z_G1 ,"\n")
cat("MSE X,Z G2: ", MSE_X_Z_G2 ,"\n")
cat("MSE X,Z G3: ", MSE_X_Z_G3 ,"\n")
cat("MSE X,Z G4: ", MSE_X_Z_G4 ,"\n")


erroresXY = vector(mode="numeric", length=0)
erroresXZ = vector(mode="numeric", length=0)





for(i in 1:1001){ 
    erroresXY[i] = datos[i+0,]$Y - funcionXY(-501+i)
    erroresXZ[i] = datos[i+0,]$Z - funcionXZ(-501+i)
}

X = seq(from = -500, to = 500, by = 1)
df <- data.frame(X, erroresXY, erroresXZ)


ggplot() + 
  geom_line(data = df, 
            aes(x = X, y = erroresXY, 
                color = "Errores XY")) + 
  geom_line(data = df, 
            aes(x = X, y = erroresXZ, 
                color = "Errores XZ")) +
     labs(colour = "Varibles") + ggtitle("Error Regresión V/S Valor Verdadero") + 
    xlab("X") + ylab("Error")


MSE X,Y G1:  24.80513 
MSE X,Y G2:  24.74417 
MSE X,Y G3:  28.66382 
MSE X,Y G4:  23.71739 
MSE X,Z G1:  6891489288 
MSE X,Z G2:  4261172346 
MSE X,Z G3:  4287602198 
MSE X,Z G4:  6782356562 


MSE X,Y G1:  24.80513 

MSE X,Y G2:  24.74417 

MSE X,Y G3:  28.66382 

MSE X,Y G4:  23.71739 



MSE X,Z G1:  6891489288 

MSE X,Z G2:  4261172346 

MSE X,Z G3:  4287602198 

MSE X,Z G4:  6782356562 


Podemos ver que para el modelo X,Y el MSE tiene valores varios ordenes de magnitud menores que para X,Z esto se debe a que como vemos en el gráfico en la pregunta anterior, Y tiene un comportameinto lineal, mientras que Z tiene la forma de una parabola, por tanto como se ve, el MSE en los extremos de X,Z es aun mayor que el MSE en los puntos medios (G3,G4)

>i) Calcule un intervalo de confianza con un 90%, 95% y 99% nivel de confiabilidad en el modelo XY si $x=10$

In [20]:
# Utilizando Y|X=Xo

esperado = funcionXY(10)

#summary(ModeloXY) # Obtener grados de libertad

tstudent_90 =  pt(0.05, 999, lower.tail = F)
tstudent_95 =  pt(0.025, 999, lower.tail = F)
tstudent_99 =  pt(0.005, 999, lower.tail = F)

SSE <- sum( ModeloXY$resid^2 )

desviacion = sqrt(SSE/999)

x <- datos$X

sxx <- sum((x-mean(x))^2)


raiz = sqrt(1+ 1/1001 + (10 - mean(datos$X))**2/sxx  )


menor_90 = esperado - tstudent_90*desviacion*raiz
mayor_90 = esperado + tstudent_90*desviacion*raiz

menor_95 = esperado - tstudent_95*desviacion*raiz
mayor_95 = esperado + tstudent_95*desviacion*raiz

menor_99 = esperado - tstudent_99*desviacion*raiz
mayor_99 = esperado + tstudent_99*desviacion*raiz



cat("Intervalo con 90% confianza [", menor_90,",",mayor_90, "]\n")
cat("Intervalo con 95% confianza [", menor_95,",",mayor_95, "]\n")
cat("Intervalo con 99% confianza [", menor_99,",",mayor_99, "]\n")




Intervalo con 90% confianza [ 20.71685 , 25.37915 ]
Intervalo con 95% confianza [ 20.66846 , 25.42754 ]
Intervalo con 99% confianza [ 20.62973 , 25.46627 ]


Intervalo con 90% confianza [ 20.71685 , 25.37915 ]

Intervalo con 95% confianza [ 20.66846 , 25.42754 ]

Intervalo con 99% confianza [ 20.62973 , 25.46627 ]


>**O:** j) Muestre que el modelo XY es válido mediante un test de hipótesis.

### 2.2 Bootstrap (40 p)

Suponga que tiene una muestra  **M** de una población **P** y esta muestra **M** es de tamaño **N**. Queremos obtener algún estimador $ \theta $ de **P** a partir de **M** ya sea la media, varianza, o alguna otra función que interese, obviamente este estimador tendrá un error asociado ya que no es el estimador de la población. Uno de los métodos para determinar intervalos de confianza es el método bootstrap que permite trabajar solamente con una muestra de la población.

Podemos entender bootstrap de la siguiente manera: Suponga que tenemos en una bolsa papelitos con cada elemento de la muestra **M**, sacamos un papelito, **lo volvemos a guardar en la bolsa** y repetimos este proceso **N** veces hasta tener una muestra $M^{1*}$ y sobre esta muestra de la muestra aplicamos la función que queremos conocer (media, varianza, etc) teniendo un estimador $ \theta ^{1*} $ . Luego repetimos este proceso **B** veces y terminamos con un conjunto de **B** estimadores. 

En esta sección solamente trabajará con la columna X y la columna Y del conjunto de datos "datos.csv".

>k) Dada la naturaleza de los datos (datos.csv), la primera muestra (de la que se realizan los remuestreos posteriormente) ¿puede ser cualquier muestra? ¿Por qué?

Por que ambos siguen una distribución normal 

>l) Se le pide encontrar un intervalo de confianza Bootstrap para los coeficientes del modelo $(a,b)$ de regresión lineal XY obtenido en 2.1, utilizando una confiabilidad de 90%, 95% y 99%. Utilice bootstrap **a mano**.

*Hint: Esto involucra realizar varios modelos de regresión acorde a las muestras*

* Explique bien su procedimiento
* Tenga especial atención con la muestra y muestra de la muestra.
* Se recomienda que lo desglose en múltiples celdas para mayor entendimiento y si falla sea más fácil retroceder a donde se produce el error.
* Puede comparar con los coeficientes obtenidos en 2.1 para verificar que tan bien están sus intervalos.
* Como construir un intervalo de confianza bootstrap queda en manos del alumno investigar dicho tema.

In [8]:
# Función para Obtener la muestra de la muestra


getM = function () {
    
    Y = vector()
    X = vector()

    for(i in 1:10){ 
        posicion = sample(nrow(datos), 1);
        Y[i] = datos[posicion, ]$Y
        X[i] = datos[posicion, ]$X
    }
    return(data.frame(X,Y))
}


# Obtener los B estimadores
B = 1000

VectorEstimadoresA = vector()
VectorEstimadoresB = vector()
#VectorSumasXi2  = vector()
#VectorSumasXi  = vector()
for(i in 1:B){ 
    df = getM()
   
    modelo = lm(Y ~ X, data=df) 
    #Obtener estimador a,b de la regeresión
    est_a = coef(summary(modelo))["(Intercept)","Estimate"]
    est_b = coef(summary(modelo))["X","Estimate"]
    
    
    VectorEstimadoresA[i] = est_a
    VectorEstimadoresB[i] = est_b
   # VectorSumasXi2[i] = sum(df$X^2)
   # VectorSumasXi  = sum(df$X)
    
    
}





In [9]:
#Calculo de Constantes

SXY = 0
SXX = 0
promedioy = mean(datos$Y)
for(i in -500:500){ 
    SXX = SXX+ i^2
    SXY = SXY + i^2* (datos[i+501,]$Y - promedioy)
    
}

tstudent_90 =  pt(0.05, grados, lower.tail = F)
tstudent_95 =  pt(0.025, grados, lower.tail = F)
tstudent_99 =  pt(0.005, grados, lower.tail = F)



In [12]:
# Para B0



b0 = mean(VectorEstimadoresA)

grados = length(VectorEstimadoresA) - 2


#summary(ModeloXY) # Obtener grados de libertad


SSE <- sum( VectorEstimadoresA^2 )


desviacion = sqrt(SSE/grados)

#suma_xi = sum(datos$X^2)

final = desviacion * sqrt(SSE) / (grados+2) * sqrt(SXX)



menor_90 = b0 - tstudent_90*final
mayor_90 = b0 + tstudent_90*final

menor_95 = b0 - tstudent_95*final
mayor_95 = b0 + tstudent_95*final

menor_99 = b0 - tstudent_99*final
mayor_99 = b0 + tstudent_99*final



cat("Intervalo para A con 90% confianza [", menor_90,",",mayor_90, "]\n")
cat("Intervalo para A con 95% confianza [", menor_95,",",mayor_95, "]\n")
cat("Intervalo para A con 99% confianza [", menor_99,",",mayor_99, "]\n")

Intervalo para A con 90% confianza [ -1635.314 , 1641.311 ]
Intervalo para A con 95% confianza [ -1669.317 , 1675.314 ]
Intervalo para A con 99% confianza [ -1696.536 , 1702.533 ]


Intervalo con 90% confianza [ -6.412901 , 12.55146 ]

Intervalo con 95% confianza [ -6.609704 , 12.74826 ]

Intervalo con 99% confianza [ -6.767241 , 12.9058 ]

In [11]:
# Calculo de Intervalos

#para B1

SSE <- sum( VectorEstimadoresB^2 )
grados = length(VectorEstimadoresB) - 2



desviacion = sqrt(SSE/grados)

final = desviacion/sqrt(SXX)


b1 = SXY/SXX


menor_90 = b1 - tstudent_90*final
mayor_90 = b1 + tstudent_90*final

menor_95 = b1 - tstudent_95*final
mayor_95 = b1 + tstudent_95*final

menor_99 = b1 - tstudent_99*final
mayor_99 = b1 + tstudent_99*final



cat("Intervalo para B con 90% confianza [", menor_90,",",mayor_90, "]\n")
cat("Intervalo para B con 95% confianza [", menor_95,",",mayor_95, "]\n")
cat("Intervalo para B con 99% confianza [", menor_99,",",mayor_99, "]\n")


Intervalo para B con 90% confianza [ 0.1854983 , 0.1857087 ]
Intervalo para B con 95% confianza [ 0.1854962 , 0.1857109 ]
Intervalo para B con 99% confianza [ 0.1854944 , 0.1857126 ]


Intervalo para B con 90% confianza [ -2.790768 , 6.792333 ]

Intervalo para B con 95% confianza [ -2.890217 , 6.891781 ]

Intervalo para B con 99% confianza [ -2.969823 , 6.971388 ]

## 3. Bonus para todos Gradiente Descendiente

**Este ejercicio otorgará 30 puntos a la peor nota de los laboratorios 1 a 3. Pero solamente aplicará si la nota de este laboratorio (lab 4) es igual o superior a 65.**

¿Recuerda el problema de los soldados presentado en el laboratorio 2?

Utilizando gradiente descendente encuentre el tamaño de agrupación de soldados óptimo que minimice el costo del tratamiento. El tamaño del grupo que se le dió aumentaba el costo, pero pueden existir tamaños mejores que puedan incluso lograr un costo más barato y debe verificar/refutar esto utilizando el algoritmo de gradiente descendiente.

Recuerde enunciar el contexto del problema y el modelado del fenómeno. 

## Reglas del Juego y Comentarios 

+ Celda de código que no ejecute anula la respuesta a todas las preguntas contenidas en esa celda a partir de la falla
+ Errores ortográficos, de redacción y oraciones ambiguas descontarán 1 punto c/u, con límite de 50 puntos. 
+ **Dudas solamente hasta el día Martes 18 de Diciembre a las 15:00. (De ahí en adelante: Google)**
+ Dudas **principalmente** vía moodle, evite otro tipo de medio ya que su duda podría ser la de otro.
+ Cada día de atraso descuenta 25 puntos de la nota final con un máximo de dos días de retraso (después es 0).
+ La versión de R que se usará para revisar es 3.4.3
+ La versión de Python que se usará para revisar es 3.6.5
+ Los alumnos malla nueva que decidan responder las preguntas opcionales (obviando algún bonus para todos) tendrán 1 punto bonus por pregunta correctamente respondida, con un máximo de nota 100.
+ Use cualquier librería que estime conveniente, si requiere de instalación explicitarlo en el README (y bien explicitado).
+ Código comentado para facilitar entendimiento.
+ Sea formal y claro con su respuesta, explique su procedimiento y luego responda. 
+ Intente mantener un carácter científico durante la elaboración de su notebook.
+ Defina bien las secciones de su notebook [Tips para usar Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)